### ISSUE TITLE
What does <your-device> mean?

### ISSUE THREAD

**Issue by sunpengfei001** [jackyzengl/GRID#2]
Hi there,
      How should the parameter value of --gpu_device be set in the command [python run_preprocess_data.py --gpu_devices <your device>], and what does<your device>mean? Can you briefly explain and give an example? 
      Looking forward to your reply!

**Comment by Leib-Niz** [comment]
The meaning of the --gpu_devices parameter is to set the ID number of the GPU device(s) to be used. The detailed explanation can be found in the def create_parser() function of the arguments.py file.

Note that when using the train.py script, the device ID can be set to multiple values, separated by ",", which means that multiple GPUs will be used for training. However, when using the run_preprocess_data.py script, the ID can only be set to a single value, because preprocessing does not support parallel processing on multiple GPUs.

For example, to use GPU device 1 for preprocessing, the command would be:
python run_preprocess_data.py --data_path /path/to/data --gpu_devices 1

To use GPU device 0 for preprocessing, the command would be:
python run_preprocess_data.py --data_path /path/to/data --gpu_devices 0
